# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63846629c443019fdbd350e9da2319232976ae54772ec3c92bd7ba19267abc471e0edbcbd32258c691d769711595d90d05821e2381bad30fa885728efa45cc61

test:
  secret_key_base: 1ae49db87e921bef7727909bc3ab121835e248851f286b5c67cc4f0ce3cf6484470fb9658208d7853d3abcc54e4d999a22b3a98d8e7889ecfc47221a4e182936

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
